package com.example.lifeeasy.ui.screens.auth

import android.content.Context
import android.util.Log
import androidx.credentials.ClearCredentialStateRequest
import androidx.credentials.CredentialManager
import androidx.credentials.GetCredentialRequest
import androidx.credentials.GetCredentialResponse
import androidx.credentials.exceptions.GetCredentialCancellationException
import androidx.credentials.exceptions.GetCredentialException
import androidx.credentials.exceptions.NoCredentialException
import com.google.android.libraries.identity.googleid.GetGoogleIdOption
import com.google.android.libraries.identity.googleid.GoogleIdTokenCredential
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext

class GoogleAuthHandler(private val context: Context) {

    companion object {
        private const val TAG = "GoogleAuthHandler"
    }

    private val credentialManager = CredentialManager.create(context)

    suspend fun signIn(): String? {
        return withContext(Dispatchers.Main) {
            try {
                // Fetch the web client ID from strings (auto-generated by google-services plugin)
                val resId = context.resources.getIdentifier(
                    "default_web_client_id", "string", context.packageName
                )

                if (resId == 0) {
                    Log.e(TAG, "default_web_client_id not found in resources. " +
                            "Make sure you have added a Web App OAuth Client ID in Firebase Console " +
                            "and re-downloaded google-services.json with the oauth_client section populated.")
                    return@withContext null
                }

                val serverClientId = context.getString(resId)
                Log.d(TAG, "Using server client ID: ${serverClientId.take(20)}...")

                val googleIdOption = GetGoogleIdOption.Builder()
                    .setFilterByAuthorizedAccounts(false)
                    .setServerClientId(serverClientId)
                    .setAutoSelectEnabled(true)
                    .build()

                val request = GetCredentialRequest.Builder()
                    .addCredentialOption(googleIdOption)
                    .build()

                val result = credentialManager.getCredential(
                    context = context,
                    request = request
                )

                handleSignInResult(result)
            } catch (e: NoCredentialException) {
                Log.e(TAG, "No Google accounts available on this device", e)
                null
            } catch (e: GetCredentialCancellationException) {
                Log.d(TAG, "User cancelled Google Sign-In")
                null
            } catch (e: GetCredentialException) {
                Log.e(TAG, "GetCredentialException: ${e.type} - ${e.message}", e)
                null
            } catch (e: Exception) {
                Log.e(TAG, "Unexpected error during Google Sign-In", e)
                null
            }
        }
    }

    private fun handleSignInResult(result: GetCredentialResponse): String? {
        val credential = result.credential
        return try {
            val googleIdTokenCredential = GoogleIdTokenCredential.createFrom(credential.data)
            Log.d(TAG, "Google Sign-In successful for: ${googleIdTokenCredential.displayName}")
            googleIdTokenCredential.idToken
        } catch (e: Exception) {
            Log.e(TAG, "Failed to extract Google ID token", e)
            null
        }
    }

    suspend fun signOut() {
        try {
            credentialManager.clearCredentialState(ClearCredentialStateRequest())
        } catch (e: Exception) {
            Log.e(TAG, "Error clearing credential state", e)
        }
    }
}
